version: '3'

services:

  mariadb:
    image: 'mariadb:10.7'
    restart: on-failure
    hostname: 'mariadb'
    environment:
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: pass
    volumes:
      - 'mariadb:/var/lib/mysql:rw'
    expose:
      - '3306'

  adminer:
    image: 'adminer:latest'
    restart: on-failure
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - '8080:8080'

  ms-backend:
    image: ghcr.io/suniastar/ms-address:0.1.0-SNAPSHOT
    restart: on-failure
    environment:
      DATABASE_URL: jdbc:mariadb://mariadb:3306/db
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
    ports:
      - '80:8080'

volumes:
  mariadb:
